### ISSUE TITLE
Configure typos cli to ignore "ine"

### ISSUE THREAD

**Issue by TadoTheMiner** [ratatui-org/ratatui#1023]
## Description

Multiple PRs fail the lint check because of typos cli thinks that "ine" should be "one". I think we should configure it to accept it, even though it could result in False Negatives. And you can configure it to ignore specific files. Maybe it's possible to configure it so that it ignores "ine" in just the file it's in.

## Environment

- OS:
- Terminal Emulator:
- Font:
- Crate version:
- Backend:

**Comment by joshka** [comment]
See #1022. It's better to keep typos accurate and choose inputs that wrap to actual words. This was simple enough to add a single letter to fix the bug ("little" instead of "short").

If typos supported a scoped ignore, that would be best (it doesn't), but it's generally valuable to have typos caught and not have to add random partial words.
