### ISSUE TITLE
Layout: Ability for a layout chunk to grow and shrink automatically

### ISSUE THREAD

**Issue by pythops** [ratatui-org/ratatui#125]
## Problem

The layout chunk size are static by default.

## Solution
Having a new constraints that allow a chunk to grow and or shrink based on its content. The new constraints should allow to define the min and max size for the chunk. Additionally, it would be great to have an indicator that the size of the chunk content is larger than the size of the chunk itself and hence enable the scrolling automatically. 

## Alternatives
An alternative is to update the chunk constraints for each step of the loop.

**Comment by joshka** [comment]
Over in https://github.com/tui-rs-revival/ratatui/pull/155 @karthago1 has introduced a SizeHint trait that might partially impact some of the ideas mentioned in this issue (by giving widgets the capability to report the size that they'd like to draw to so that widgets inside a list )

**Comment by joshka** [comment]
(Triaging the issues list)

This request asks for the following features (rephrased):
1. Layouts to be calculated based on widget content rather than based on a mathematical property of the containing area
2. Layout to be able to have multiple constraints per chunk (e.g. MinMax(1,10) or similar)
3. Layout of the content to be able to interact with the calculated layout to display differently

From an implementation perspective:
1. Requires adding some functionality to layout widgets, either an extra method for layout purpose that runs earlier than the render method, or a SizeHint approach. I think this is probably difficult to do well and requires a lot of fundamental changes. Perhaps a `LayoutManager` struct / module, some new methods in the Widget trait(s), or a new Trait for handling such things.
2. Requires either specific new Constraints (`Constraint::MinMax(1,10)`) or composite constraints (`Constraint::All([Constraint::Min(1), Constraint::Max(10))`). I prefer the latter and think it's feasible to do and widely applicable
3. This would be a per widget thing, and basically relates to the Scrolling RFC https://github.com/ratatui-org/ratatui/issues/174 more than anything. (Widgets should be able to render their scroll UI whenever their requested layout doesn't match their actual layout)

On the alternatives front:
1. I'm exploring some of these ideas in [Tui-Brûlée](https://github.com/joshka/tui-brulee) (slowly). This is a small crate that will be a taffy based approach to laying out UIs. This is more complex than our existing approach and enables lots of things including the idea of measuring content to fit the space rather than splitting space by maths. It implements the CSS grid and Flex standards. I think this is a better use of time than trying to bolt on some of this in Ratatui, but the ideas may cross pollinate over time.
2. Not sure there's any alternative other than just using math.
3. https://crates.io/crates/tui-scrollview is a way to wrap a widget in a scrollable area if the desired size is known. Virtual buffer copied into the main buffer on each frame with the right scroll position applied.

Todo:
- [ ] Contribute ideas to tui-brulee
- [ ] Implement `Constraint::All` (and/or other composite constraints)
- [ ] Work more on the scroll RFC to completion

@pythops, unless you have other ideas on this, I think it's worth closing this issue by just doing the the second action, and defer the others to other places where they make sense (or splitting this issue to be more specific on those ideas)

**Comment by pythops** [comment]
Agree.
