### ISSUE TITLE
ListItem highlight style overwrites inner span styles

### ISSUE THREAD

**Issue by jfoucher** [ratatui-org/ratatui#422]
## Description

When a `ListItem` contains `Line`s made up of styled `Span`s, and selecting the ListItem, the `highlight_style`from the outer `List` overrides any styles set on the Spans.

## To Reproduce

Replace lines 217-220 of https://github.com/ratatui-org/ratatui/blob/main/examples/list.rs with the following:
```
Line::from(vec![
    Span::styled("Green background", Style::default().bg(Color::Green)),
    Span::from("Rest of line")
])
```

## Expected behavior

The text "Green background" should keep a green background.

## Screenshots

<img width="605" alt="Capture d’écran 2023-08-20 à 23 32 03" src="https://github.com/ratatui-org/ratatui/assets/152015/58e0bcda-6201-40f3-83eb-3da8a325d426">

## Environment

- OS: macOs Ventura 13.4
- Terminal Emulator: iTerm2
- Font: UbuntuMono Nerd Font
- Crate version: 0.22
- Backend: crossterm

**Comment by jfoucher** [comment]
As a workaround, it is possible to find out if the particular ListItem is selected while generating its contents, and apply different styles depending on whether it is selected or not, and then not use the ListItem's highlight_style function.

**Comment by joshka** [comment]
This is the expected behavior of the way highlighting works. To confirm this consider what the effect would be if every line had the same style information and had both foreground and background specified (this is a fairly common case). How would a highlight style be visible at all?

Yes, you can do that by looking at `ListState::selected()` prior to rendering.

I can't think of a reasonable way to configure this feature otherwise without some more complex design - perhaps an extra variable everywhere style is used that puts a priority on which style is used when rendering? The list highlight is already an additive style (i.e. if the list style sets the background and the highight style just sets the foreground/modifier, then the background will not be reset.

**Comment by jfoucher** [comment]
My intuition was that the inner styles would overwrite the outer ones, but since the workaround is not so bad, I'm going to close this for now. Thanks for the answer.
