### ISSUE TITLE
`BarChart` example in `docs.rs` cannot be compiled

### ISSUE THREAD

**Issue by fadeevab** [ratatui-org/ratatui#448]
## Problem

This line causes a compilation error: https://github.com/ratatui-org/ratatui/blob/3f781cad0ad7e0d6284be0af8dc6c1e0ba7e71b4/src/widgets/barchart/mod.rs#L24

## Measure
The following syntax should be used instead (as in the actual `BarChart` example):
```rust
.bar_style(Style::default().fg(Color::Yellow))
```

**Comment by Valentin271** [comment]
Modifying the `BarChart` example to the following compiles fine on my machine.

```rust
    let barchart = BarChart::default()
        .block(Block::default().title("Data1").borders(Borders::ALL))
        .data(&app.data)
        .bar_width(9)

        .bar_style(Style::new().yellow().on_red())

        .value_style(Style::default().fg(Color::Black).bg(Color::Yellow));
    f.render_widget(barchart, chunks[0]);
```

![image](https://github.com/ratatui-org/ratatui/assets/36198422/df0a1184-3635-45e0-9d4b-e26bed578314)

---

Is the compilation failing on docs.rs or on your machine?

If it fails on you machine, did you include the [`Stylize`](https://docs.rs/ratatui/0.23.0/ratatui/style/trait.Stylize.html) trait or the Ratatui prelude?

**Comment by fadeevab** [comment]
@Valentin271 Right, I haven't included the `Stylize` trait, I didn't know it existed. The best thing would be to make the doc examples compilable.

**Comment by joshka** [comment]
> @Valentin271 Right, I haven't included the Stylize trait, I didn't know it existed. The best thing would be to make the doc examples compilable.

This comment is interesting because it suggests a couple of things (and that the [Curse of Knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge) is present):
- The style shorthand approach (implemented via the `Stylize` trait) is not discoverable. https://docs.rs/ratatui/latest/ratatui/style/#using-style-shorthands is the current docs for this.
- Although we have a tendency to use the [prelude](https://docs.rs/ratatui/latest/ratatui/prelude/index.html) for examples, this isn't something that is necessarily discoverable or obvious either. (The `Stylize` trait is included in the prelude).

In https://github.com/ratatui-org/ratatui/pull/447#pullrequestreview-1599229844 I suggested that we generally should use both those approaches, but I'm concerned that these might need a little tweak perhaps. Maybe we need to add some sort of 'See also' to each style section for the `Stylize` problem, and perhaps for the first example in each type we should include the necessary imports (and prelude to make it more visible).

**Comment by Valentin271** [comment]
I agree, it's always hard to document something you know.

I think the use of the prelude is a good thing. My understanding of the prelude is that you should always include the one from the lib you're working with. So maybe this is what we need to document: that the Ratatui prelude actually exists. I'd start by mentioning it on the main doc page.

However, as you said I think we should see more often the `use prelude` in the examples to help beginners. Generally, I'd hide every non specific import in every example except `mod` or `type` level ones. 

---

After taking a more in depth look at the docs, the `Stylize` trait definitely need to be more discoverable. Currently, you'll find it pretty much only if you know it.

To address that, again I agree, we should cross reference items more. This should probably be a thing for all items rather only `Stylize`.

---

**As a sum up of my post**

- Document the prelude existence (and maybe usage? link to the [rust doc](https://doc.rust-lang.org/reference/names/preludes.html#extern-prelude)?)
- Show non-obvious imports in examples (notably traits)
& show every import in `mod` and `type` level examples?
- More cross-reference

**Comment by fadeevab** [comment]
@Valentin271 Just my 5 cents, I usually never start with a `prelude::*`, many libraries don't provide a `prelude`, and even with `ratatui` I easily started without it, having just all types included directly. Usually, I'd love to know how to use concrete traits and where the declarations go from. To cut a long story short, good documentation should help with this challenge, just as you stated. Thanks!
