### ISSUE TITLE
Docs - landing page Layout section is out of place -> not newcomer friendly

### ISSUE THREAD

**Issue by 1oglop1** [ratatui-org/ratatui#512]
## Description
As a newcomer to Rust and Ratatui, I go to the documentation page https://docs.rs/ratatui/latest/ratatui/
The first few lines show perfect examples of what I can do with the library, then follow the minimal working example.
But then the `Layout` section contains some function `ui()` which explains how elements are composed,
however, the function example is completely disconnected from the previous code block, which makes it hard to grasp what is going on without diving deeper into the code.

## Expected behavior
I'd expect the landing page to either provide a complete example or at least point me in the direction of examples. 
Pointing to examples should not just be a text, but rather a link to a repo or page which explains more details about how to use
the library.

**Comment by joshka** [comment]
Thanks, this is some great feedback. Writing better docs is something that we're all working on (and would appreciate all the help you can spare).

If you haven't already found the following, these resources are available:
- The Readme: https://github.com/ratatui-org/ratatui#quickstart (has a more complete example)
- the Ratatui book: https://ratatui-org.github.io/ratatui-book/index.html
- the examples: https://github.com/ratatui-org/ratatui/tree/main/examples
- Several templates / samples:
  - https://github.com/ratatui-org/rust-tui-template
  - https://github.com/pmsanford/simple-tui-rs
  - https://github.com/ratatui-org/ratatui-async-template

Ideally these should be better cross linked in all the right places so concretely we need to:
- [ ] Compare the README and docs.rs main page and ensure that they are either consistent or link to each other appropriately (we could either make these exactly the same, or simplify one and point to the other, but we need to understand which bits are useful in each first). [cargo-rdme](https://crates.io/crates/cargo-rdme) is possibly something to consider here
- [ ] Ensure that mentions of "examples" actually link to the examples
- [ ] Ensure that we link to the Book more
- [ ] Highlight the available templates
- [ ] Ensure that the various docs page links all to the other docs (no dead ends)
- [ ] Document the examples more (this is a larger task)

Happy to hear more suggestions on this / take PRs if you're interested in helping out.

**Comment by 1oglop1** [comment]
Thanks! I will look into it.

I'd like to contribute back when I get a hang of the project. Because the examples look pretty good. It's just a pity they are a bit hidden. 
I am not a fan of a separate rust book because it is one more place to look at and maintain the parity. 

I hope that the suggested solution here will soon become a reality Because it's pretty much standard in other languages (e.g. python->Sphinx) 
 https://internals.rust-lang.org/t/rustdoc-include-an-external-markdown-file-as-a-separate-page/15994

**Comment by joshka** [comment]
> I'd like to contribute back when I get a hang of the project. Because the examples look pretty good. It's just a pity they are a bit hidden.

If you like the look of the current examples, check out PR #500 for some inspiration.

Rendered versions of the examples (in the examples Readme) have only been since the end of July PR #303 - before that you had to run the examples yourself to see what they looked like. I actually want this to go a few steps further and use the rendered examples directly in the docs.

> I am not a fan of a separate rust book because it is one more place to look at and maintain the parity.

One of the major things that dictates a separate repo rather than just the docs.rs api docs for us is that the speed of iteration on docs is 1-2 of magnitude faster than of the library. (78 PRs merged since June when the book started compared with just 3 releases of ratatui in the last 4 months). We won't be moving away from having a book, but we'll definitely try to keep the right sort of linkage between them.

> I hope that the suggested solution here will soon become a reality Because it's pretty much standard in other languages (e.g. python->Sphinx)

That does sound neat for some things. Clap is an example that the docs.rs approach leads to something 

> I hope that the suggested solution here will soon become a reality Because it's pretty much standard in other languages (e.g. python->Sphinx)

Sounds interesting.

**Comment by kdheepak** [comment]
For reference, [clap's landing page](https://docs.rs/clap/latest/clap/):

<img width="910" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/b2fb6215-d0bf-4283-93c1-4c9f55239c74">

has links to start off with + one code example with no explanations (which I like) further down the page. 

It gives people as idea of what kind of syntax is required to use this package just to recognize patterns without any deeper prose or explanations (for example, we talk about crossterm and termion and terminal backends in the first few lines; the example has a thread spawn with event read which probably no one will use in real code; there's a line at the end about computed layouts and blank spaces; etc which is all not required for users or potential users that are just landing on the page for the first time).

Serde goes one step further: no code examples on the landing page + a single line that tells users to do to https://serde.rs for additional examples (which happens to be a mdbook generated website):

<img width="910" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/512657c1-38df-415b-98dd-985e522441d3">

I really like that approach.

**Comment by joshka** [comment]
Some subjective observations:
- People tend to link to one of {crate page, docs page, github repo} when linking a lbrary, so ideally they should have the same information on them to avoid communicating different things on each page.
- I tend to use the information on those pages as a metric for whether to invest further in learning a particular crate, so the initial information should be compelling enough to dig deeper. When I view a crate page for something TUI related, I want to see the following:
  - What it looks like
  - What it does (a list of all high level features)
  - A basic code example (not a tutorial walk through, but only enough to help me know which main types I need to know about) - this led to the code example in https://github.com/ratatui-org/ratatui#quickstart
  - MSRV
  - Links to related crates

The docs / readme don't need Cargo.toml examples or info on alternate backend config. That belongs elsewhere.
It would be nice to have a small image of each widget  (~20x3 cell) to show what each can do, I think it's good to have these on the main landing pages instead of at a secondary link, but these could also go on the widgets module page if we think there's too much info.

**Comment by a-kenji** [comment]
Please also keep the text editor side in mind. The main way I interact with the documentation is through an `lsp` popup window.
That makes is also very trivial to copy parts of examples that are surfaced in doc comments and adjust them amongst other things.

**Comment by joshka** [comment]
> Please also keep the text editor side in mind. The main way I interact with the documentation is through an `lsp` popup window.
> That makes is also very trivial to copy parts of examples that are surfaced in doc comments and adjust them amongst other things.

Good call out - can you screenshot some examples? It would be helpful to have an example of how the docs render right now via the LSP.

**Comment by kdheepak** [comment]
For me in neovim:

<img width="948" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/b8a84214-3fc0-4dad-a68e-bc2abbd00ed6">

**Comment by joshka** [comment]
Neat. Thanks :)
